categories:
  - Metabolomics
description: "[Metabolomics][DIMS] DIMSpy: Tools for processing, filtering and analysing direct-infusion mass spectrometry-based metabolomics and lipidommics data"
long_description: "[Metabolomics][DIMS] DIMSpy: Tools for processing, filtering and analysing direct-infusion mass spectrometry-based metabolomics and lipidomics data"
name: dimspy
owner: computational-metabolomics
remote_repository_url: https://github.com/computational-metabolomics/dimspy-galaxy
homepage_url: https://github.com/computational-metabolomics/dimspy-galaxy
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "[Metabolomics][DIMS] DIMSpy: {{ tool_name }} {{ description }}"
suite:
  name: "suite_dimspy"
  description: "[Metabolomics][DIMS] DIMSpy: Tools for processing, filtering and analysing direct-infusion mass spectrometry-based metabolomics and lipidomics data"
  long_description: "[Metabolomics][DIMS] DIMSpy: Tools for processing, filtering and analysing direct-infusion mass spectrometry-based metabolomics and lipidomics data"
  type: repository_suite_definition
